version: '2'

services:
  bokehapp:
    env_file:
      - 'variables.env'
    build:
      context: .
      dockerfile: bokehapp.Dockerfile
    depends_on:
      - flaskapp
    ports:
      - '5006:5006'
    volumes:
      - './:/app'
  flaskapp:
    env_file:
      - 'variables.env'
    build:
      context: .
      dockerfile: flaskapp.Dockerfile
    volumes:
      - './:/app'
    ports:
      - '80:5000'

